meilisearch/meilisearch-go

client.go, client_documents_test.go, client_search_test.go, client_settings_test.go
The method has been changed to add two things:
- A context to manipulate from the outside when the function should stop polling the status of an update id.
- A interval duration to configure the time between each poll. 
A simplified method called `AwaitAsyncUpdateIDSimplified` set default to `AwaitAsyncUpdateID` with a timeout of `5 seconds` and a interval of `50ms`. 
Resolve issue #10
=> Improvement: Method AwaitAsyncUpdateID

client.go, client_documents_test.go
It always returned all documents regardless of query params set
perform request with the required query params vs as a payload
=> Fix 🐛 Documents.List()

client.go
With the changes introduced by the v0.11 of MeiliSearch, requests will receive an error from API: `Unsupported media type`
This PR fixes this by adding a header "Content-Type" with value "application/json" which is backward compatible with other versions (tested v0.9 and v0.10)
=> Add 'application/json' as content media type

client_search.go
As for now, search requests are sending every possible parameter, even those that are unused. For example, searching with a query "term" and a limit of 10 build the following request:
`GET /indexes/:indexUid/search?attributesToCrop=&attributesToHighlight=&attributesToRetrieve=&cropLength=0&filters=&limit=10&matches=false&offset=0&q=term`
This PR modifies this behavior with a hotfix, as this will be broken with the v0.11. That request would be built as:
`GET /indexes/:indexUid/search?limit=10&q=term`
I call it hotfix because the goal of this PR is to make it compatible as fast as possible, but we might want to find a better and cleaner solution for this
=> hotfix: only send required parameters for search

client.go
The new server in MeiliSearch doesn't handle empty parameters. Each parameter should be sent only if it has a value to avoid having a wrong response.
In this case, `attributesToRetrieve` was being sent even if the list of attributes was empty. This PR is a hotfix to not send this parameter unless it has some content.
=> hotfix: empty params in Documents().List()

apis.go, client_documents_test.go, client_search.go, client_search_test.go, client_settings.go, client_settings_test.go, types.go
For obvious reasons, tests won't pass as faceting is not compatible with the current latest release (v0.10.1)
=> Implement faceting

client_search_test.go, types.go
=> Add NbHits as int64 to SearchResponse

client_documents.go
Issue detailed in #55 
`List` method parameters (`limit`, `offset` and `attributesToRetrieve`) should be optional, and shouldn't be sent on the request unless the user has set them to a specific value
Closes #55
=> Make client List() parameters optional

client_search.go
Use `POST` route instead of `GET` for search method
Note: `attributesToHighlight`, `attributesToRetrieve` and `attributesToCrop` must always be a list (array) instead of a string so it is properly deserialized by the server
facetFilters and facetsDistribution can be sent as is, and no need to transform into string
Closes #64
=> Implement POST route in search method

client_search.go, client_search_test.go, types.go
About this PR: 
As defined in https://github.com/meilisearch/MeiliSearch/pull/771, MeiliSearch will implement placeholder search starting with v0.13.0
A search request containing no Query parameter (or a null value in that parameter) will send a response with a basic placeholder search showing ranked results, and will be as customizable as any other search request.
GO types and default initialization to zero value doesn't let us make a clear distinction between an uninitialized String (some `nil` value) and an empty String (some `""` value) when all we are handling is a string. We need to be able to provide those two options in order to implement placeholder search, which expects no `q` parameter (no query) or a null value.
An option to do this would be using a string pointer that can be …
=> Implement placeholder search. Update tests

client_search_test.go
This PR:
- fails in this CI because the MeiliSearch's release v0.15.0 is not out
- should work locally with the [prerelease v0.15.0rc2](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.15.0rc2)
=> Update tests for MeiliSearch v0.15.0

.github/workflows/check.yml, bors.toml, go.mod, go.sum
This PR introduces a 2 jobs test in the CI:
- one with the current go version of meilisearch-go module (1.12, set in `go.mod`)
- a second one with the latest stable go version (1.15 as of today).
It uses `include` in the GitHub Actions to add a tag system that uses the word `current` instead of `1.12` and `latest` instead of `1.15` to make it easy to automate GitHub and Bors checks by using always stable names. 
This way, for example, a job isn't called 
```
Check / integration-tests with go 1.12 version
```
but 
```
Check / integration-tests with go current version
```
For example, by changing the tests version from `1.12` -> `1.13` we won't need to update the repo nor the bors settings to do all the CI + checks, a simple version number change will work out-of-the-box! 🎉 
NOTE: It also …
=> Run build and test on current go.mod version and latest stable go version

.editorconfig, .github/workflows/pre-release-tests.yml, .github/workflows/tests.yml, bors.toml
Add CI for the pre-release PRs = PRs to `bump-meilisearch-v*`. This CI will run the tests against the MeilliSearch RC instead of the MeiliSearch `latest`.
For each PR to `bump-meilisearch-v*`:
- the `linter` job will run
- the `integration-tests-against-rc` job will run
- the `integration-tests` job will be skipped
- the required jobs (for merging) in the settings will be: `linter` and `integration-tests-against-rc`
For each **push** to `bump-meilisearch-v*`:
- the `linter` job will run
- the `integration-tests-against-rc` job will run
- the `integration-tests` job will run
- the required jobs (for merging) in the settings will be: `linter` and `integration-tests`
For any other event (PRs and pushes):
- the `linter` job will run
- the `integration-tests-against-rc` job will NOT run
- the …
=> Add CI for pre-releases

.code-samples.meilisearch.yaml
Code sample for creating an index doesn't exactly match other SDK code samples, as it this one is not using the primary key as a parameter.
=> Fix error in code samples

README.md, client.go, client_request.go, client_test.go, main_test.go
close #160 
Not breaking because a roll back in the same release
=> Rename MasterKey by ApiKey

README.md, client.go, client_request.go, client_test.go, main_test.go
Like it was!
Not breaking because a rollback in the same release
=> Rename ApiKey by APIKey

types.go, types_easyjson.go
Rename fields `buildDate` 
Change it into `string` instead of `time.Time`
=> Rename buildDate to commitDate

.code-samples.meilisearch.yaml, index_search.go, index_search_test.go, types.go, types_easyjson.go
Query parameter: `Filter` now allow string and array
=> Update Filter field

client_index_test.go, client_test.go, go.sum, index_test.go
This PR changes the way of comparing `Error` objects in tests. It compares only `MeilisearchApiMessage.ErrorCode`.
Also removes unused import and redundant type declarations.
Closes #198
=> Tests error compare fix

client_index_test.go, index_test.go
Added checks in related test cases to make sure that `createdAt` and `updatedAt` fields in `Index` are always filled when expected. These checks are currently passing, so the `Index` values returned should be correct already. 
Fixes #209
=> Make sure that `createdAt` and `updatedAt` are correctly update in `Index`

index.go
Fix the confused comment on `IndexConfig.Uid`.
=> Fix the confused comment on uid

client_request.go, index_documents.go
This adds verifications into `Client.sendRequest()` to make sure that request bodies are always set up as expected:
- GET and HEAD requests should not have a request body
- All requests with request bodies should have a Content-Type set
Running the tests with the new checks highlighted an issue in `Index.getDocuments()` which is fixed as well.
=> Make request body handling consistent

CONTRIBUTING.md
Before running the test, we should enforce this command. Indeed, because of the cache, running the same tests against two different versions of MeiliSearch will not behave as expected: the second run will give the exact same result as the second one.
=> Add clean cache command in CONTRIBUTING.md

client_test.go, types.go, types_easyjson.go
This change helps to make the status field more consistent between "Update" and "Dump" and fixes #242.
The UpdateStatus field is an enum, but the DumpStatus field is a string. 
In the docs, these fields have a set number of possibilities and that's why it'd be proper to make DumpStatus an enum, rather than a string.
=> Convert the dump status to an enum

client_request.go, index.go, index_documents.go, index_documents_test.go
This completes the biggest part of #215 and adds the requested new methods for document insertion together with new test cases. Additionally some extra methods were added which receive `io.Reader` to provide a more idiomatic interface, especially for batch requests.
If this approach is approved, I can easily add the document update methods as well.
=> Add methods for new document formats

client.go, client_index.go, client_index_test.go, client_request.go, client_test.go, index.go, index_documents.go, index_documents_test.go, index_search_test.go, index_settings.go, index_settings_test.go, index_test.go, main_test.go, types.go, types_easyjson.go
All the actions on indexes are now asynchronous:
- `CreateIndex()`, `UpdateIndex()`, `DeleteIndex()` return a `Task` response instead of an `Index`.
- `index.Create` and `index.Delete` from index return a `task`.
- `WaitForPendingUpdate()`
- is renamed into `WaitForTask`
- the current `index.WaitForTask()` method call `/tasks/:uid`
- `index.GetUpdateStatus` is renamed `index.GetTask`
- `index.GetAllUpdateStatus` is renamed `index.GetTasks`
**Notes:** The only two methods that now return an `Index` are `client.Index()` and `client.GetIndex()`
- new method `client.WaitForTask()` call `/tasks/:uid`
- new method `client.WaitForTask()`
- new method `client.GetTasks` that calls `/tasks`
- new method `client.GetTask` that calls `/tasks/:uid`
=> Redesign update API to task API

client.go, client_test.go, main_test.go, types.go, types_easyjson.go
Granular management of API keys is now added to MeiliSearch. New methods have been created to manage this:
- `client.GetKey` get information about a specific API key.
- `client.CreateKey` create a new API key.
- `client.DeleteKey` delete an API key.
- `client.UpdateKey` update an API key.
Modification:
- `client.GetKeys`
=> Addition related to API keys

client.go, client_test.go, go.mod, go.sum, main_test.go, types.go, types_easyjson.go
Introduction of the new method `GenerateTenantToken`  in order to facilitate the generation of the tenant token.
Related to:
- this issue: https://github.com/meilisearch/meilisearch/issues/1991
- this spec: https://github.com/meilisearch/specifications/pull/89
=> Adding GenerateTenantToken method to the client 

.github/workflows/tests.yml
Update the `golangci/golangci-lint` version because of a `typecheck` error
=> Fix CI linter by updating the version

.github/scripts/check-release.sh, .github/workflows/release-check.yml, CONTRIBUTING.md
Since the adoption of this new release system *(now we need to update the version of the constant defined in the version.go file). We now need to validate that we are following this step.
Related to #279
=> Add a new Github workflow step to release

index_search_test.go
Following this [issue](https://github.com/meilisearch/meilisearch/pull/2298), the order in which the document is returned has changed.
=> Fix tests due to changing the way of returning documents

index_search_test.go, main_test.go, version_test.go
Add tests on nested fields to ensure it is still maintained in Meilisearch.
=> Ensure nested field support

index_search.go, index_search_test.go, types.go, types_easyjson.go
As per https://github.com/meilisearch/meilisearch/issues/2214 new search parameters are introduced: 
- `highlightPreTag`
- `highlightPostTag`
- `cropMarker`
=> Add new search parameters highlightPreTag, highlightPostTag and cropMarker

index_search_test.go, index_settings.go, index_settings_test.go, main_test.go, types.go, types_easyjson.go
This PR introduces the new setting: [typoTolerance](https://github.com/meilisearch/specifications/pull/117)
new methods: 
`Index.GetTypoTolerance()`
`Index.UpdateTypoTolerance(params)`
`Index.ResetTypoTolerance()`
closed #288
=> Add typo tolerance settings

.code-samples.meilisearch.yaml, README.md, index_search.go, index_search_test.go, types.go, types_easyjson.go
- Rename `nbHits` response parameter to `estimatedTotalHits`.
- Delete `exhaustiveNbHits` response parameter.
- Delete `exhaustiveFacetsCount` response parameter.
- `matches` request parameter is renamed `showMatchesPosition`.
- `facetsDistribution` request parameter is renamed `facets`.
- `facetsDistribution` response parameter is renamed `facetDistribution`.
=> Apply search changes

index.go, index_settings.go
Breaking because enforces the users to use Meilisearch v0.28.0
- `PATCH` `/indexes/{indexUid}` instead of `PUT`
- `PATCH` `/indexes/{indexUid}/settings` instead of `POST`
- `PATCH` `/indexes/{indexUid}/settings/typo-tolerance` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/displayed-attributes` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/distinct-attribute` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/filterable-attributes` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/ranking-rules` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/searchable-attributes` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/sortable-attributes` instead of `POST`
- `PUT` `/indexes/{indexUid}/settings/stop-words` instead of `POST`
- `PUT` …
=> Change HTTP methods

.code-samples.meilisearch.yaml, client.go, client_test.go
Related to: https://github.com/meilisearch/integration-guides/issues/205
Breaking because enforces the users to use Meilisearch v0.28.0
=> Apply dumps changes

.code-samples.meilisearch.yaml, client.go, client_test.go, main_test.go, types.go
Related to: https://github.com/meilisearch/integration-guides/issues/205
Breaking because enforces the users to use Meilisearch v0.28.0
- `PATCH /keys/:uid_or_key` can update **only** `name` and `description` fields.
=> Apply keys changes

client.go, client_test.go, main_test.go, types.go
as per the [spec](https://github.com/meilisearch/specifications/pull/148/files#diff-7b1a49daa5acb02c131aff3eb5fabb81c7e7c3d1b95adb60c4bf70cadcb488d4)
=> Apply tenant changes

.code-samples.meilisearch.yaml, index.go, index_documents.go, index_documents_test.go, types.go
Related to: https://github.com/meilisearch/integration-guides/issues/205
Breaking because enforces the users to use Meilisearch v0.28.0
- `GET /documents/:uid`, `GET /documents` Add the possibility to reduce the body payload by using a query parameter called `fields` (previously called `attributesToRetrieve`), check the issue and the spec for the entire behavior.
- The documents objects in now return wrap in a `results`
=> Apply documents changes

.code-samples.meilisearch.yaml, index.go, index_documents.go, index_documents_test.go, types.go
Add pagination parameters to the `GetDocument()` method
And DocumentQuery struct
=> Add fields parameters to the GetDocument() method

.github/workflows/tests.yml
The GitHub action who run `run golangci-lint` failed with this error:
```
Running [/home/runner/golangci-lint-1.45.2-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
level=error msg="[runner] Panic: buildir: package \"atomic\" (isInitialPkg: false, needAnalyzeSource: true): T: goroutine 7731 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()\n\tgithub.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:101 +0x155\npanic({0xf853e0, 0xc001fcad50})\n\truntime/panic.go:838 +0x207\nhonnef.co/go/tools/go/ir.(*Program).needMethods(0xc001bfe9a0, {0x1226ec8?, 0xc001fcad50?}, 0x0)\n\thonnef.co/go/tools@v0.2.2/go/ir/methods.go:237 …
```
=> Fix linter in github action

.github/workflows/tests.yml, client.go, types.go, types_easyjson.go
The deletion of dumps had not been done correctly this PR solves this problem and remove useless struct and method
=> Remove properly GetDumpStatus and Dump struct

client.go, client_test.go, types.go, types_easyjson.go
`type Key struct {}` and `type KeyParsed struct {}` both have a `Key string` field.
However, `KeyParsed`'s one is never filled and thus the server always will generate a random key, even if a value was specified in the call to `client.CreateKey(&meilisearch.Key{Key: "..."}}`.
=> Create key: Add ability to specify the `Uid` and `Name` value

.code-samples.meilisearch.yaml
I added the TypoTolerance struct type to options brackets and capitalized the I in the Index function. A detailed description is in the issue.
Fixes https://github.com/meilisearch/meilisearch-go/issues/344
=> docs: fix code samples for typo tolerance

client_test.go
Ensure support to keys with wildcarded actions.
- `actions` field during key creation now accepts wildcards on actions. For example, `indexes.*` provides rights to `indexes.create`, `indexes.get`,`indexes.delete`, `indexes.delete`, and `indexes.update`.
=> Add tests to wildcarded action keys

version.go
This version makes this package compatible with Meilisearch v0.29.0 :tada:
Check out the changelog of [Meilisearch v0.29.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.29.0) for more information on the changes.
- Ensure support to the new search query parameter `MatchingStrategy` (#348) @brunoocasali 
- Ensure support to keys with wildcarded actions.
- `actions` field during key creation now accepts wildcards on actions. For example, `indexes.*` provides rights to `indexes.create`, `indexes.get`,`indexes.delete`, `indexes.delete`, and `indexes.update`. (#349) @brunoocasali 
This breaking change *__may not affect you__*, but in any case, you should check your search queries if you want to keep the same behavior from `v0.28`.
- The `NOT` filter keyword does not have an …
=> Release v0.21.0

.code-samples.meilisearch.yaml
This commit adds code samples for the MatchingStrategy field of a SearchRequest.
Closes #368
Fixes #368
- adds code samples for using "last" and "all" as `MatchingStrategy` in a `SearchRequest`
=> add code samples for matching strategy

client_request.go, error.go, go.mod, go.sum, index_documents.go
Package github.com/pkg/errors has been marked deprecated.
Fixes #378
- Remove references to github.com/pkg/errors
=> Remove references to github.com/pkg/errors

.code-samples.meilisearch.yaml, index_documents.go
Package io/ioutil has been marked deprecated in Go 1.16.
Fixes #380 
- Removes references to io/ioutil
=> Remove references to io/ioutil

main_test.go
The `Test_deleteAllIndexes` wasn't waiting for the index Creation which would generate an error
=> Fix Test delete all indexes

.code-samples.meilisearch.yaml, client.go, client_test.go, index.go, main_test.go, types.go, types_easyjson.go
Add new filters on the `get /tasks` route.
Present in this [spec](https://github.com/meilisearch/specifications/pull/195)
V0.30.0
in TasksQuery:
Tests:
=> Add tasks filters for v0.30

index_search.go, index_search_test.go, types.go, types_easyjson.go
Adds the new page selection component 
TODO: 
Response: 
Tests
=> Add pagination feature for v0.30.0

client.go, client_test.go, types.go, types_easyjson.go
Add the delete task api see spec:  https://github.com/meilisearch/specifications/pull/198
- params: `TasksQuery`
- returns: `TaskInfo`
=> Add delete task api for v0.30.0

client.go, client_test.go, types.go, types_easyjson.go
As [per the specification](https://github.com/meilisearch/specifications/pull/192)
- params: TasksQuery
- returns: TaskInfo
=> Add swap indexes api for v0.30.0

client.go, client_test.go, types.go, types_easyjson.go
Add the cancel task api see spec:  https://github.com/meilisearch/specifications/pull/195
- params: `TasksQuery`
- returns: `TaskInfo`
=> Add cancel task api for v0.30.0

version.go
This version makes this package compatible with Meilisearch v0.30.0 :tada:
Check out the changelog of [Meilisearch v0.30.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.30.0) for more information on the changes.
- New `pagination` strategy with the search parameters `Page` and `HitsPerPage` #392
- New filters on `GetTasks`: `UID`, `BeforeEnqueuedAt`, `AfterEnqueuedAt`, ... see #390 
- New `client.CancelTasks` method that lets you cancel `enqueued` and `processing` tasks #395
- New `client.DeleteTasks` method that lets you delete tasks #396 
- New `client.SwapIndexes` method that lets you swap two indexes #397
- New fields on `Task.Details` #395
- Parameters on `GetTasks` name changes: #390
- `Status` -> `Statuses`
- `IndexUID` -> `IndexUIDS`
- `Type` -> `Types`
=> Update version for the next release (0.22.0)

.code-samples.meilisearch.yaml
Two keys were duplicated in the [`.code-samples.meilisearch.yaml`](https://github.com/meilisearch/meilisearch-go/blob/main/.code-samples.meilisearch.yaml) files. 
Resulting in a badly formatted YAML file, which led to the documentation not being able to render Go's samples.
fixes: #401
=> Remove duplication of keys in code-samples.meilisearch.yaml

.code-samples.meilisearch.yaml, .github/dependabot.yml, .github/workflows/pre-release-tests.yml, .github/workflows/release-check.yml, .github/workflows/tests.yml, .yamllint.yml
To ensure no yaml file are broken, I added a linter test on the yaml files. 
This ensures they are correctly formated and correctly linted.
To test it locally you need to use the [`yamllint` tool](https://github.com/adrienverge/yamllint) and then run it like that:
```
yamllint .
```
Example of output
=> Add yaml linter test in ci

version.go
This version makes this package compatible with Meilisearch v1.0.0 🎉
Check out the changelog of [Meilisearch vv1.0.0](https://github.com/meilisearch/meilisearch/releases/tag/v1.0.0) for more information on the changes(https://github.com/meilisearch/meilisearch-go/pull/405).
* KeyParsed struct has been changed; this structure is used to manage the time format when creating a key, however, all the `Key` fields were available in the structure, while only those used to create a key should be available in it.
- `createdAt` has been removed
- `updatedAt` has been removed
Thanks again to @Thearas, @alallema, @bidoubiwa! 🎉
=> Update version for the next release (v0.23.0)

index_documents.go
Fixes #<issue_number>
- Improve robustness
Call ```client.Index("movies").AddDocuments(movies, []string{}...)``` will panic.
=> Avoid panic when sending `(...[]string{})` in `AddDocument()`

client.go, client_test.go, index_search.go, types.go, types_easyjson.go
Now Meilisearch can perform multiple searches in one single HTTP request.
A new method has been added to the [specifications](https://github.com/meilisearch/specifications/pull/225):
`MultiSearch(queries MultiSearchRequest) (*MultiSearchResponse, error)`
The method takes `[]SearchRequest` as argument:
```go
m := []meilisearch.SearchRequest{}
m = append(m, meilisearch.SearchRequest{
IndexUid: "movies",
Query: "wonder",
})
client.MultiSearch(m)
```
SDK requirements: https://github.com/meilisearch/integration-guides/issues/251
=> Add multiple searches

index.go, index_documents.go, index_documents_test.go, types.go, types_easyjson.go
Add the ability to provide a CSV delimiter for adding and updating CSV documents as in the [specification](https://github.com/meilisearch/specifications/pull/221)
SDK requirements: https://github.com/meilisearch/integration-guides/issues/251
All these methods taking `CSV` have changed
**Changes:**
- New type `CsvDocumentsQuery{}`
- `AddDocumentsCsv(documents []byte, primaryKey ...string) (resp *TaskInfo, err error)`
-> `AddDocumentsCsv(documents []byte, options *CsvDocumentsQuery) (resp *TaskInfo, err error)`
- `AddDocumentsCsvInBatches(documents []byte, batchSize int, primaryKey ...string) (resp []TaskInfo, err error)`
-> `AddDocumentsCsvInBatches(documents []byte, batchSize int, options *CsvDocumentsQuery) (resp []TaskInfo, err error)`
- `UpdateDocumentsCsv(documents []byte, primaryKey …
=> Configure Csv delimiter

client_index.go
- Fills in the `client` field for every `Index` entry returned by `GetIndexes`. If left empty the resulting indexes cannot be used to query parameters of the index, update settings, etc.
=> fix(indexes): Fill in `client` for `GetIndexes` results

error.go, error_test.go, index_documents.go, index_documents_test.go, types.go, types_easyjson.go
As per the specification: https://github.com/meilisearch/specifications/pull/234
- Add ability to `GetDocuments` with a filter
- Add the `filter` field on the `DocumentsQuery` struct
- The `filter` is an `interface{}` which allows you to send different types of filters (`string`, `[]string`, `[]interface{}{[]string{}}`, ...)
The `filter` field works precisely like the `filter` field used on the `search` method. See [the docs on how to use filters](https://www.meilisearch.com/docs/learn/advanced/filtering#filter-basics).
=> Adds filter to the parameters for GetDocuments - Meilisearch v1.2

codecov.yml, index_search.go, index_search_test.go, main_test.go, types.go, types_easyjson.go
=> Add support for vectorSearch (v1.3)

.code-samples.meilisearch.yaml
I created [scripts to manage code samples](https://github.com/meilisearch/integration-automations/pull/164) (internal only)
1. I found out the following code samples are still in this repo but not used by the documentation anymore, so I removed them:
```bash
meilisearch-go
- 'get_keys_1' not found in documentation
- 'documents_guide_add_movie_1' not found in documentation
- 'getting_started_communicating_with_a_protected_instance' not found in documentation
- 'faceted_search_facets_1' not found in documentation
- 'faceted_search_2' not found in documentation
- 'date_guide_Index_1' not found in documentation
```
2. I found the following code samples were missing:
```bash
meilisearch-go
- 'get_all_keys_1' not found
- 'date_guide_index_1' not found
- 'async_guide_canceled_by_1' not found
- …
```
=> Remove useless code samples and add missing ones

index.go
*None*
Add `DeleteDocumentsByFilter` method to `IndexInterface` to be able to use the method through the interface.
https://github.com/meilisearch/meilisearch-go/blob/3310833cd68e1fd42c9f63e9028edf41410e5b5c/index_documents.go#L535
Without this change, the following document doesn't work as expected.
=> Enable to use `DeleteDocumentsByFilter` through `IndexInterface`

index_search_test.go, types.go, types_easyjson.go
Fixes -
- Changes the type of `SearchRequest.Vector` to a `[]float32`, as it aligns more with meilisearch and general embedding vectors.
=> Alligned `SearchRequest.Vector` type to `[]float32`

.code-samples.meilisearch.yaml, index_search.go, index_search_test.go, types.go, types_easyjson.go
Fixes #518
- Add the search parameter `showRankingScoreDetails` introduced in [`Meilisearch v1.7.0`](https://github.com/meilisearch/meilisearch/releases/tag/v1.7.0) 
=> Add new search param showRankingScoreDetails

.code-samples.meilisearch.yaml, index_facet_search.go, index_facet_search_test.go, types.go, types_easyjson.go
Fixes #470
- Implements Facet Search introduced on version 1.3 
Reference: https://www.meilisearch.com/docs/reference/api/facet_search
=> Add facet search method

.code-samples.meilisearch.yaml, index.go, index_settings.go, index_settings_test.go, types.go, types_easyjson.go
Fixes #507
- This PR support `proximityPrecision` setting
=> Feat support proximityPrecision setting

.code-samples.meilisearch.yaml, index_search_test.go, main_test.go, types.go, types_easyjson.go
Fixes #540
- This PR accept the frequency value for the matchingStrategy search
=> Feat accept the frequency value for the matchingStrategy search

types.go, types_easyjson.go
Partial fix for #576
The documentation for the Ollama Embedder states that there is an `url` field that can be used to specify how Ollama can be reached. However, this field is not present yet in this client library.
See: https://www.meilisearch.com/docs/learn/experimental/vector_search#generate-auto-embeddings
=> Add Embedder.URL

meilisearch_test.go, types.go, types_easyjson.go
Fixes #573
This PR adds support for the new federated search to be introduced in v1.10: https://github.com/meilisearch/meilisearch/releases/tag/v1.10.0-rc.0
=> Add multi-search federation

README.md, client.go, client_bench_test.go, client_test.go, error.go, meilisearch.go, options.go, options_test.go
Fixes #569
- Add retry pattern logic in client as default can manage retry pattern via options.
=> Feat support retry pattern on status code 502, 503, 504

index_search_test.go, index_settings_test.go, types.go
Fixes #578 
- Makes the `hybrid.embedder` field mandatory everywhere.
=> [v1.11.0] Make the embedder mandatory everywhere

encoding.go, encoding_bench_test.go, meilisearch.go, meilisearch_interface.go, meilisearch_test.go
- Fix return buffers to the pool after use
- Add encoding and decoding benchmark
- Improve naming convention
=> Enhance encoding algorithm and improve naming convention

index_settings_test.go, types.go, types_easyjson.go
Fixes #576 
- Update the embedders types + tests according to v1.10 
- Fix name convation for "APIKey" instead "ApiKey".
=> Add AI-powered search changes related to v1.10

index_task.go, index_task_test.go, types.go, types_easyjson.go
Fixes #596
- Allow passing "reverse" to the get tasks endpoint.
=> GetTasks: allow for reverse param

types.go, types_easyjson.go
Fixes #613 
- Adds `usedDatabaseSize` key to `stats`
=> Adds usedDatabaseSize key to stats

types.go, types_easyjson.go
Fixes #614 
- Adds indexes.INDEXNAME.numberOfEmbeddedDocuments in SDK responses
- Adds indexes.INDEXNAME.numberOfEmbeddings in SDK responses
=> Adds embeddings database metrics to stats

index_test.go, types.go, types_easyjson.go
Fixes #615 
- Adds `indexes.INDEXNAME.rawDocumentDbSize` in SDK responses
- Adds `indexes.INDEXNAME.avgDocumentSize` in SDK responses
=> Adds document database metric to stats object
