- README.md
> Fix getting started example

- client.go
- client_documents.go
Issue #43 describe the problem. This pull request resolve the security issue.
> Fix security issue with query parameters

- client_documents_test.go
- main_test.go
> Implement deleteAllIndexes() in tests, use before and after running tests

- README.md
> Update readme with golint clarification

- .github/workflows/go.yml
- client_documents_test.go
- client_health_test.go
- client_indexes_test.go
- client_keys_test.go
- client_search_test.go
- client_settings_test.go
- client_stats_test.go
- client_updates_test.go
- client_version_test.go
- main_test.go
- run_tests.sh
Example of the new CI FAIL
https://github.com/meilisearch/meilisearch-go/pull/57/checks?check_run_id=821123687
Master tests will fail until #56  gets merged
Closes #40 
Closes #51
> Update tests CI

- CONTRIBUTING.md
- README.md
- run_tests.sh
Related to this issue https://github.com/meilisearch/integration-guides/issues/33.
> Add CONTRIBUTING.md

- .code-samples.meilisearch.yaml
- apis.go
- types.go
Removes sys-info route
Closes #63
> Remove sys-info route

- CONTRIBUTING.md
- README.md
Add instructions to pull latest docker image in README.md and CONTRIBUTING.md
> Update docker instructions in README and CONTRIBUTING

- .code-samples.meilisearch.yaml
- apis.go
- client.go
- client_settings.go
- client_settings_test.go
- types.go
⚠️ Tests will not pass until v0.13.0 of MeiliSearch is released
Closes #72
> Update settings following the settings behavior changes on MeiliSearch

- .code-samples.meilisearch.yaml
> Add code samples for documentation

- README.md
- client_search_test.go
This PR:
- should work locally with the [prerelease v0.15.0rc0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.15.0rc0)
⚠️ This PR should not be merged until the MeiliSearch's release v0.15.0 is out.
> Changes about the MeiliSearch's next release (v0.15.0)

- apis.go
- client_health.go
- client_health_test.go
> Remove the PUT /health routes

- CONTRIBUTING.md
See meilisearch/meilisearch-js#687
> Update docker in CONTRIBUTING.md

- .code-samples.meilisearch.yaml
- apis.go
- client.go
- client_dumps.go
- client_dumps_test.go
- types.go
- types_easyjson.go
Implementation for /dumps https://github.com/meilisearch/meilisearch-go/issues/82
> Add dumps endpoint support

- index_search.go
- types.go
- types_easyjson.go
- Use filter instead of filters
- Remove facetFilters
- filter/facet on number are now doable
- Some parts of the code-samples are changed or commented, this will change in the future according to the docs
> Rename Filters into Filter

- types.go
- types_easyjson.go
Adding `startedAt` and `finishedAt` fields inside Dump struct
> New fields in dumps routes

- .code-samples.meilisearch.yaml
> Fix broken yaml code sample file

- .code-samples.meilisearch.yaml
Update search code sample for clarity related to [this issue](https://github.com/meilisearch/integration-guides/issues/124)
> Update code samples for clarity

- .code-samples.meilisearch.yaml
Fix a lot of mistake in code sample
> Fix new search query in code sample

- .github/workflows/pre-release-tests.yml
- .github/workflows/tests.yml
- CONTRIBUTING.md
- client_test.go
- error.go
- go.mod
- go.sum
- index.go
- index_documents.go
- types.go
- Fixes #186
- Update meilisearch version to 0.21.1
- Update Go to supported versions
> Linter update

- client_test.go
> Fixing health test for local run

- README.md
Added an example using the filtering feature to the README as requested in the linked issue.
Fixes #216
> Add example for search with filters

- .code-samples.meilisearch.yaml
- Add `settings_guide_sortable_1`
- Fix all the `settings_guide` with `udpateSettings()` instead of the sub setting route method.
> Update code sample setting guide sortable

- client_index.go
- client_index_test.go
- client_request.go
- client_test.go
- error.go
- index.go
- index_test.go
> Change MeilisearchApiMessage to MeilisearchApiError

- types.go
- types_easyjson.go
Fixes #249
This PR fixes the new JSON formatting for the /stats endpoint
> Fix the /stats response json unmarshaling

- client_request.go
> Use Authorization header instead of X-Meili-API-Key

- client.go
- client_test.go
- index.go
- index_test.go
> Rename type waitParams to WaitParams for making it exported

- client.go
- client_test.go
> Fix fasthttp client name typo

- client.go
- client_test.go
- go.mod
- go.sum
Reduce the probability of issue #221 occurrence.
For more info see the discussion at fasthttp: <https://github.com/valyala/fasthttp/issues/1315#issuecomment-1147875793>
> Reduce the probability of connection reset

- client.go
- client_index.go
- index.go
- index_documents.go
- index_documents_test.go
- index_settings.go
- index_settings_test.go
- main_test.go
- types.go
- types_easyjson.go
The idea of this PR is to create two separate structures to handle the `Task` as a resource: the return of the `GET /tasks` route and `TaskInfo` the return of all async routes.
> Refactoring Task ressource

- index_settings.go
- index_settings_test.go
- main_test.go
- types.go
- types_easyjson.go
> Add pagination settings

- .code-samples.meilisearch.yaml
- index_settings.go
- index_settings_test.go
- main_test.go
- types.go
- types_easyjson.go
> Add faceting settings

- .code-samples.meilisearch.yaml
Based on the comments from #329 this adds code samples for the pagination settings added in #328.
It also includes some typo fixes from the additions in #294.
> Add pagination setting code samples and fix code sample typos

- README.md
I fixed sample code. `task.taskUID` to `task.TaskUID`.
Fixes #346
> Fix REAME.md sample code typo

- client_test.go
- docker-compose.yml
- main_test.go
Fixes #365 
-  changes the name of environmental variable as suggested in the mentioned issue
> Rename MEILISEARCH_HOST to MEILISEARCH_URL

- client_test.go
None.
No skipping `ConnectionCloseByServer` test. (The test I added in PR #303)
> No skipping `ConnectionCloseByServer` test

- index.go
- index_documents.go
- index_documents_test.go
> Implement update methods CSV & NdJson

- index.go
- index_test.go
Fixes #209 
- Updates `Index` variable when the tracked data is updated
> Syncing Index

- types.go
Fixes #636
- Added Total Tasks in task route
> Total Tasks in task route #636

- .code-samples.meilisearch.yaml
- index_search.go
- index_search_test.go
- types.go
- types_easyjson.go
> Add support for rankingScore (v1.3)

- client.go
No issue, all changes described in this PR
Using the `select` statement with channels is considered more idiomatic Go than using `time.Sleep`, and also enables the waiting to be interrupted by context cancellation in the middle of a polling interval.
Performance-wise both options are similar (see [here](https://stackoverflow.com/a/32148983/394526)).
> Make `client.WaitForTask` use select and channels for polling

- .code-samples.meilisearch.yaml
- client.go
- client_index_test.go
- client_test.go
- index.go
- index_documents_test.go
- index_test.go
- types.go
- types_easyjson.go
Fixes #491 
This PR addresses the lack of clear definitions for `TaskType` in our asynchronous task definition. While `TaskStatus` is well-defined, `TaskType` currently uses generic strings which could lead to confusion and maintenance challenges. By providing a definitive list of types, we enhance clarity, improve code readability, and set the groundwork for easier maintenance in future SDK versions.
The Meilisearch Go client has undergone a significant enhancement in how it handles task types and statuses. In prior versions, developers interfaced with tasks using generic strings. This methodology, while functional, lacked clarity and posed maintenance challenges.
`TaskType` and `TaskStatus` have transitioned from generic strings to definitive constants. This change augments code …
> feat!: enhanced enumeration for task types & statuses

- client_test.go
- index_search_test.go
- types.go
- types_easyjson.go
- Add DumpUid on task details.
> Add `DumpUid` field for `dumpCreation` task.

- codecov.yml
This is the attempt to force a minimum code coverage in this repo
https://docs.codecov.com/docs/coverage-configuration
> Apply cov range to avoid flaky failures

- client.go
- client_test.go
- main_test.go
https://github.com/meilisearch/meilisearch-go/issues/522
Fixes #522
- fixes ticker CPU leakage on the WaitForTask method. I also optimized the method to first check and then start a ticker if needed. Also added some missing unit test for the GetTasks method using the the client package, which is totally unrelated but needed to get to the codecov threshold
> Fix issue with ticker leaking CPU, optimize

- .code-samples.meilisearch.yaml
- index_search.go
- index_search_test.go
- types.go
- types_easyjson.go
Fixes #539
- Add the search parameter rankingScoreThreshold introduced in [Meilisearch v1.9.0](https://github.com/meilisearch/meilisearch/releases/tag/v1.9.0)
> Add rankingScoreThreshold search parameter

- index_settings_test.go
- types.go
- types_easyjson.go
Fixes #452 
- This make fix bug allow disable typo tolerance.
> Fix allow typo tolerance to be disabled for an index

- .code-samples.meilisearch.yaml
- index_search.go
- index_search_test.go
- main_test.go
- types.go
- types_easyjson.go
Fixes #542
- This PR accept distinct search parameter, Refer to [docs for more information](https://www.meilisearch.com/docs/reference/api/search#distinct-attributes-at-search-time).
> Add distinct search parameter

- .code-samples.meilisearch.yaml
- index.go
- index_settings.go
- index_settings_test.go
- types.go
- types_easyjson.go
Fixes #530 
- This PR make support `searchCutoffMs` settings, Refer to [docs for more information](https://www.meilisearch.com/docs/reference/api/settings#search-cutoff).
> Add `searchCutoffMs` setting

- .code-samples.meilisearch.yaml
- index.go
- index_search.go
- index_search_test.go
- types.go
- types_easyjson.go
Fixes #541 
- This PR get similar documents, Refer to [docs for more information](https://www.meilisearch.com/docs/reference/api/similar#get-similar-documents-with-post).
> Feat get similar documents

- client.go
- client_test.go
- index_search.go
- index_search_test.go
- types.go
- types_easyjson.go
- types_test.go
Resolves #531, resolves #536
- This PR add json tags to request/query types
> Fix add json tag on search request

- .code-samples.meilisearch.yaml
- meilisearch.go
- meilisearch_test.go
Fixes #501
- Add a new method for creating snapshots
> Add method to create snapshot

- .code-samples.meilisearch.yaml
- index.go
- index_settings.go
- index_settings_test.go
- types.go
- types_easyjson.go
Fixes #488
- Support text-separator customization
> Feat support text-separator customization

- .code-samples.meilisearch.yaml
- index.go
- index_settings.go
- index_settings_test.go
- types.go
- types_easyjson.go
Fixes #489
- This PR Support user-dictionary loading
> Add dictionary settings

- .code-samples.meilisearch.yaml
- index_interface.go
- index_settings.go
- index_settings_test.go
- types.go
- types_easyjson.go
Fixes: https://github.com/meilisearch/meilisearch-go/issues/595
> Add PrefixSearch and FacetSearch settings
